default_context:
  full_name: "Hervé Beraud"
  email: "herveberaud.pro@gmail.com"
  github_username: "microservice-projects"
  project_name: "System Footprint"
  project_slug: "system_footprint"
  project_short_description: "Security System Scanner Footprint Dockerized"
  pypi_username: "4383"
  version: "0.1.0"
  use_pytest: "n"
  use_pypi_deployment_with_travis: "y"
  command_line_interface: "Click"
  create_author_file: "y"
  open_source_license: "GNU General Public License v3"
  tool: "nmap"
  docker_command: "nmap -A -T4"
  features: "Nmap Port Scanning"
